[project]
name = "nakobot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-auth>=2.47.0",
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "pytelegrambotapi>=4.29.1",
    "python-dotenv>=1.2.1",
]
